apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: db-project-001

labels:
  - pairs:
      app.kubernetes.io/part-of: casino-ai-use-case-portal
      app.kubernetes.io/managed-by: gitops
    includeSelectors: true

resources:
  - namespace.yaml
  - configmap.yaml
  - settings-rbac.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/script-repo/ucdemo-001-casino/portal
    newTag: sha-bc30ed386be459c3eae024e4fc88a9637bdc7b9a
